// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Quiz.CSharp.Data;

#nullable disable

namespace Quiz.CSharp.Data.Migrations
{
    [DbContext(typeof(CSharpDbContext))]
    [Migration("20250718135359_UpdateMCQOptionCompoundKey")]
    partial class UpdateMCQOptionCompoundKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Quiz.CSharp.Data.Entities.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_collections");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_collections_code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_collections_is_active");

                    b.HasIndex("SortOrder")
                        .HasDatabaseName("ix_collections_sort_order");

                    b.ToTable("collections", (string)null);
                });

            modelBuilder.Entity("Quiz.CSharp.Data.Entities.MCQOption", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("id");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<string>("Option")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("option");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id", "QuestionId")
                        .HasName("pk_mcq_option");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_mcq_option_question_id");

                    b.ToTable("mcq_option", (string)null);
                });

            modelBuilder.Entity("Quiz.CSharp.Data.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CollectionId")
                        .HasColumnType("integer")
                        .HasColumnName("collection_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("difficulty");

                    b.Property<int>("EstimatedTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_time_minutes");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("prompt");

                    b.Property<string>("Subcategory")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subcategory");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("question_type")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)")
                        .HasColumnName("question_type");

                    b.HasKey("Id")
                        .HasName("pk_questions");

                    b.HasIndex("CollectionId");

                    b.ToTable("questions", (string)null);

                    b.HasDiscriminator<string>("question_type").HasValue("Question");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Quiz.CSharp.Data.Entities.QuestionHint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Hint")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("hint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_question_hint");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_question_hint_question_id");

                    b.ToTable("question_hint", (string)null);
                });

            modelBuilder.Entity("Quiz.CSharp.Data.Entities.TestCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExpectedOutput")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("expected_output");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("input");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_test_case");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_test_case_question_id");

                    b.ToTable("test_case", (string)null);
                });

            modelBuilder.Entity("Quiz.CSharp.Data.Entities.UserAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("answer");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<int>("TimeSpentSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("time_spent_seconds");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_answers");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_user_answers_question_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_answers_user_id");

                    b.HasIndex("UserId", "QuestionId")
                        .HasDatabaseName("ix_user_answers_user_id_question_id");

                    b.ToTable("user_answers", (string)null);
                });

            modelBuilder.Entity("Quiz.CSharp.Data.Entities.UserProgress", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.Property<int>("CollectionId")
                        .HasColumnType("integer")
                        .HasColumnName("collection_id");

                    b.Property<int>("AnsweredQuestions")
                        .HasColumnType("integer")
                        .HasColumnName("answered_questions");

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("integer")
                        .HasColumnName("correct_answers");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("LastAnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_answered_at");

                    b.Property<decimal>("SuccessRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("success_rate");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer")
                        .HasColumnName("total_questions");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId", "CollectionId")
                        .HasName("pk_user_progress");

                    b.HasIndex("CollectionId")
                        .HasDatabaseName("ix_user_progress_collection_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_progress_user_id");

                    b.ToTable("user_progress", (string)null);
                });

            modelBuilder.Entity("Quiz.CSharp.Data.Entities.CodeWritingQuestion", b =>
                {
                    b.HasBaseType("Quiz.CSharp.Data.Entities.Question");

                    b.Property<List<string>>("Examples")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("examples");

                    b.Property<List<string>>("Rubric")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("rubric");

                    b.Property<string>("Solution")
                        .HasColumnType("text")
                        .HasColumnName("solution");

                    b.ToTable("questions", (string)null);

                    b.HasDiscriminator().HasValue("CodeWriting");
                });

            modelBuilder.Entity("Quiz.CSharp.Data.Entities.ErrorSpottingQuestion", b =>
                {
                    b.HasBaseType("Quiz.CSharp.Data.Entities.Question");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correct_answer");

                    b.ToTable("questions", null, t =>
                        {
                            t.Property("CorrectAnswer")
                                .HasColumnName("error_spotting_question_correct_answer");
                        });

                    b.HasDiscriminator().HasValue("ErrorSpotting");
                });

            modelBuilder.Entity("Quiz.CSharp.Data.Entities.FillQuestion", b =>
                {
                    b.HasBaseType("Quiz.CSharp.Data.Entities.Question");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correct_answer");

                    b.Property<List<string>>("FillHints")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("fill_hints");

                    b.ToTable("questions", (string)null);

                    b.HasDiscriminator().HasValue("Fill");
                });

            modelBuilder.Entity("Quiz.CSharp.Data.Entities.MCQQuestion", b =>
                {
                    b.HasBaseType("Quiz.CSharp.Data.Entities.Question");

                    b.ToTable("questions", (string)null);

                    b.HasDiscriminator().HasValue("MCQ");
                });

            modelBuilder.Entity("Quiz.CSharp.Data.Entities.OutputPredictionQuestion", b =>
                {
                    b.HasBaseType("Quiz.CSharp.Data.Entities.Question");

                    b.Property<string>("ExpectedOutput")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("expected_output");

                    b.ToTable("questions", (string)null);

                    b.HasDiscriminator().HasValue("OutputPrediction");
                });

            modelBuilder.Entity("Quiz.CSharp.Data.Entities.TrueFalseQuestion", b =>
                {
                    b.HasBaseType("Quiz.CSharp.Data.Entities.Question");

                    b.Property<bool>("CorrectAnswer")
                        .HasColumnType("boolean")
                        .HasColumnName("correct_answer");

                    b.ToTable("questions", null, t =>
                        {
                            t.Property("CorrectAnswer")
                                .HasColumnName("true_false_question_correct_answer");
                        });

                    b.HasDiscriminator().HasValue("TrueFalse");
                });

            modelBuilder.Entity("Quiz.CSharp.Data.Entities.MCQOption", b =>
                {
                    b.HasOne("Quiz.CSharp.Data.Entities.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mcq_option_question_question_id");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Quiz.CSharp.Data.Entities.Question", b =>
                {
                    b.HasOne("Quiz.CSharp.Data.Entities.Collection", "Collection")
                        .WithMany("Questions")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questions_collections_collection_id");

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("Quiz.CSharp.Data.Entities.QuestionHint", b =>
                {
                    b.HasOne("Quiz.CSharp.Data.Entities.Question", "Question")
                        .WithMany("Hints")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_question_hint_question_question_id");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Quiz.CSharp.Data.Entities.TestCase", b =>
                {
                    b.HasOne("Quiz.CSharp.Data.Entities.Question", "Question")
                        .WithMany("TestCases")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_case_question_question_id");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Quiz.CSharp.Data.Entities.UserAnswer", b =>
                {
                    b.HasOne("Quiz.CSharp.Data.Entities.Question", "Question")
                        .WithMany("UserAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_answers_questions_question_id");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Quiz.CSharp.Data.Entities.UserProgress", b =>
                {
                    b.HasOne("Quiz.CSharp.Data.Entities.Collection", "Collection")
                        .WithMany("UserProgress")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_progress_collection_collection_id");

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("Quiz.CSharp.Data.Entities.Collection", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("UserProgress");
                });

            modelBuilder.Entity("Quiz.CSharp.Data.Entities.Question", b =>
                {
                    b.Navigation("Hints");

                    b.Navigation("Options");

                    b.Navigation("TestCases");

                    b.Navigation("UserAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
